# Use the official Redis image from the Docker Hub
FROM redis:7.4.2

# Copy the custom redis.conf file
COPY redis.conf /usr/local/etc/redis/redis.conf

# Expose the default Redis port
EXPOSE 6379

USER root
COPY init.sh /init.sh
RUN chmod +x /init.sh
ENTRYPOINT ["/init.sh"]