FROM mcr.microsoft.com/dotnet/sdk:7.0-bookworm-slim as build
WORKDIR /project
COPY . .
RUN dotnet build ./AblySink/AblySink.csproj -o /buildoutput


FROM mcr.microsoft.com/dotnet/aspnet:7.0-bookworm-slim
WORKDIR /app
COPY --from=build /buildoutput .
ENTRYPOINT dotnet AblySink.dll