FROM postgres:16

# Set environment variables for PostgreSQL (will be overridden in K8s runtime if needed)
ENV PGDATA=/app/state/pgdata
ENV POSTGRES_USER=admin
ENV POSTGRES_DB=quix

EXPOSE 5432

# Define the default command to run when starting the container
USER root
COPY init.sh /init.sh
RUN chmod +x /init.sh
ENTRYPOINT ["/init.sh"]