# Use the official Grafana image from the Docker Hub
FROM grafana/grafana:11.5.2

COPY provisioning/ /provisioning

# Set environment variables to point to /state/ folder
ENV GF_PATHS_DATA=/app/state/grafana/data \
    GF_PATHS_LOGS=/app/state/grafana/logs \
    GF_PATHS_PLUGINS=/app/state/grafana/plugins \
    GF_PATHS_PROVISIONING=/provisioning \
    GF_DASHBOARDS_PATH=/app/state/grafana/dashboards

# Set environment variables for the admin user.
ENV GF_SECURITY_ADMIN_USER=admin 


# Optionally, override Grafana's default port
ENV GF_SERVER_HTTP_PORT=3000
EXPOSE 3000

# Init container as root then switch to user Grafana
USER root
COPY init.sh /init.sh
RUN chmod +x /init.sh
ENTRYPOINT ["/init.sh"]