FROM node:14 as build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build -- --output-path=./dist/out --configuration=production

FROM nginx:1.25.3-bookworm
COPY --from=build /app/dist/out/ /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/src/assets/quix-logo.svg /usr/share/nginx/html/quix-logo.svg
RUN chown -R www-data:www-data /usr/share/nginx/html/ && chmod -R 0755  /usr/share/nginx/html/

COPY ./run_server.sh /
RUN chmod +x /run_server.sh
CMD ["/run_server.sh"]