/* 
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
 

namespace IO.Swagger.Model
{
    /// <summary>
    /// An enumeration of the types an activity may have.
    /// </summary>
    /// <value>An enumeration of the types an activity may have.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ActivityType
    {
        
        /// <summary>
        /// Enum AlpineSki for value: AlpineSki
        /// </summary>
        [EnumMember(Value = "AlpineSki")]
        AlpineSki = 1,
        
        /// <summary>
        /// Enum BackcountrySki for value: BackcountrySki
        /// </summary>
        [EnumMember(Value = "BackcountrySki")]
        BackcountrySki = 2,
        
        /// <summary>
        /// Enum Canoeing for value: Canoeing
        /// </summary>
        [EnumMember(Value = "Canoeing")]
        Canoeing = 3,
        
        /// <summary>
        /// Enum Crossfit for value: Crossfit
        /// </summary>
        [EnumMember(Value = "Crossfit")]
        Crossfit = 4,
        
        /// <summary>
        /// Enum EBikeRide for value: EBikeRide
        /// </summary>
        [EnumMember(Value = "EBikeRide")]
        EBikeRide = 5,
        
        /// <summary>
        /// Enum Elliptical for value: Elliptical
        /// </summary>
        [EnumMember(Value = "Elliptical")]
        Elliptical = 6,
        
        /// <summary>
        /// Enum Golf for value: Golf
        /// </summary>
        [EnumMember(Value = "Golf")]
        Golf = 7,
        
        /// <summary>
        /// Enum Handcycle for value: Handcycle
        /// </summary>
        [EnumMember(Value = "Handcycle")]
        Handcycle = 8,
        
        /// <summary>
        /// Enum Hike for value: Hike
        /// </summary>
        [EnumMember(Value = "Hike")]
        Hike = 9,
        
        /// <summary>
        /// Enum IceSkate for value: IceSkate
        /// </summary>
        [EnumMember(Value = "IceSkate")]
        IceSkate = 10,
        
        /// <summary>
        /// Enum InlineSkate for value: InlineSkate
        /// </summary>
        [EnumMember(Value = "InlineSkate")]
        InlineSkate = 11,
        
        /// <summary>
        /// Enum Kayaking for value: Kayaking
        /// </summary>
        [EnumMember(Value = "Kayaking")]
        Kayaking = 12,
        
        /// <summary>
        /// Enum Kitesurf for value: Kitesurf
        /// </summary>
        [EnumMember(Value = "Kitesurf")]
        Kitesurf = 13,
        
        /// <summary>
        /// Enum NordicSki for value: NordicSki
        /// </summary>
        [EnumMember(Value = "NordicSki")]
        NordicSki = 14,
        
        /// <summary>
        /// Enum Ride for value: Ride
        /// </summary>
        [EnumMember(Value = "Ride")]
        Ride = 15,
        
        /// <summary>
        /// Enum RockClimbing for value: RockClimbing
        /// </summary>
        [EnumMember(Value = "RockClimbing")]
        RockClimbing = 16,
        
        /// <summary>
        /// Enum RollerSki for value: RollerSki
        /// </summary>
        [EnumMember(Value = "RollerSki")]
        RollerSki = 17,
        
        /// <summary>
        /// Enum Rowing for value: Rowing
        /// </summary>
        [EnumMember(Value = "Rowing")]
        Rowing = 18,
        
        /// <summary>
        /// Enum Run for value: Run
        /// </summary>
        [EnumMember(Value = "Run")]
        Run = 19,
        
        /// <summary>
        /// Enum Sail for value: Sail
        /// </summary>
        [EnumMember(Value = "Sail")]
        Sail = 20,
        
        /// <summary>
        /// Enum Skateboard for value: Skateboard
        /// </summary>
        [EnumMember(Value = "Skateboard")]
        Skateboard = 21,
        
        /// <summary>
        /// Enum Snowboard for value: Snowboard
        /// </summary>
        [EnumMember(Value = "Snowboard")]
        Snowboard = 22,
        
        /// <summary>
        /// Enum Snowshoe for value: Snowshoe
        /// </summary>
        [EnumMember(Value = "Snowshoe")]
        Snowshoe = 23,
        
        /// <summary>
        /// Enum Soccer for value: Soccer
        /// </summary>
        [EnumMember(Value = "Soccer")]
        Soccer = 24,
        
        /// <summary>
        /// Enum StairStepper for value: StairStepper
        /// </summary>
        [EnumMember(Value = "StairStepper")]
        StairStepper = 25,
        
        /// <summary>
        /// Enum StandUpPaddling for value: StandUpPaddling
        /// </summary>
        [EnumMember(Value = "StandUpPaddling")]
        StandUpPaddling = 26,
        
        /// <summary>
        /// Enum Surfing for value: Surfing
        /// </summary>
        [EnumMember(Value = "Surfing")]
        Surfing = 27,
        
        /// <summary>
        /// Enum Swim for value: Swim
        /// </summary>
        [EnumMember(Value = "Swim")]
        Swim = 28,
        
        /// <summary>
        /// Enum Velomobile for value: Velomobile
        /// </summary>
        [EnumMember(Value = "Velomobile")]
        Velomobile = 29,
        
        /// <summary>
        /// Enum VirtualRide for value: VirtualRide
        /// </summary>
        [EnumMember(Value = "VirtualRide")]
        VirtualRide = 30,
        
        /// <summary>
        /// Enum VirtualRun for value: VirtualRun
        /// </summary>
        [EnumMember(Value = "VirtualRun")]
        VirtualRun = 31,
        
        /// <summary>
        /// Enum Walk for value: Walk
        /// </summary>
        [EnumMember(Value = "Walk")]
        Walk = 32,
        
        /// <summary>
        /// Enum WeightTraining for value: WeightTraining
        /// </summary>
        [EnumMember(Value = "WeightTraining")]
        WeightTraining = 33,
        
        /// <summary>
        /// Enum Wheelchair for value: Wheelchair
        /// </summary>
        [EnumMember(Value = "Wheelchair")]
        Wheelchair = 34,
        
        /// <summary>
        /// Enum Windsurf for value: Windsurf
        /// </summary>
        [EnumMember(Value = "Windsurf")]
        Windsurf = 35,
        
        /// <summary>
        /// Enum Workout for value: Workout
        /// </summary>
        [EnumMember(Value = "Workout")]
        Workout = 36,
        
        /// <summary>
        /// Enum Yoga for value: Yoga
        /// </summary>
        [EnumMember(Value = "Yoga")]
        Yoga = 37
    }

}
