FROM quixpublic.azurecr.io/devsessions-marimo:20260227.2-entrypoint-cleanup

# Copy your notebook
COPY main.py /app/main.py
COPY icon.png /app/icon.gif

# Optional: Copy additional requirements
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt
