FROM ghcr.io/quixio/marimo-base:ab130fe

# Copy your notebook
COPY main.py /app/main.py

# Optional: Copy additional requirements
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt
