FROM debian:bookworm-slim

# install CA certs for HTTPS requests
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./go_bin /app/bin
COPY ./main.sh /app/main.sh
RUN chmod +x /app/main.sh

WORKDIR /app
ENTRYPOINT ["/app/main.sh"]
