HTTP_SERVER_PORT = 8000
STREAMLIT_PORT = 80
STREAMLIT_DATAFRAME_POLL_PERIOD = 0.5
STREAMLIT_DATAFRAME_POLL_TIMEOUT = 5 * 60
STREAMLIT_DATAFRAME_REQUEST_URL = f"http://localhost:{HTTP_SERVER_PORT}"
STREAMLIT_DATAFRAME_REQUEST_TIMEOUT = 5
