name: FMU Runner
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to (simulation requests from HTTP API).
    defaultValue: simulation
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write simulation results to.
    defaultValue: simulation-results
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
