name: FMU Runner
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to (simulation requests from HTTP API).
    defaultValue: simulation
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write simulation results to.
    defaultValue: simulation-results
  - name: S3_ENDPOINT
    inputType: FreeText
    description: S3/MinIO endpoint URL for fetching FMU model binaries.
    defaultValue: http://minio:80
  - name: S3_ACCESS_KEY
    inputType: Secret
    description: S3 access key ID.
    secretKey: s3_user
  - name: S3_SECRET_KEY
    inputType: Secret
    description: S3 secret access key.
    secretKey: s3_password
  - name: S3_BUCKET
    inputType: FreeText
    description: S3 bucket name for FMU models.
    defaultValue: fmu-models
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
