{
 "title": "Sensor data",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Tire pressure sensors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"windtunnel\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pressure-alerts\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TyreSensorStatusValue\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Aggregations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 5, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"windtunnel\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pressure-alerts\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TyreSensorStatusValue\")\n  |> filter(fn: (r) => r[\"_value\"] == 0)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"windtunnel\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"aggregates\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Sum_BalanceTotal_Cz\" or r[\"_field\"] == \"Sum_BalanceTotal_Cx\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 15, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"windtunnel\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pressure-alerts\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TyreSensorStatus\")\n  |> filter(fn: (r) => r[\"_value\"] == \"Not working\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}