FROM mcr.microsoft.com/dotnet/sdk:7.0-bookworm-slim as build
WORKDIR /project
COPY . .
RUN dotnet publish ./Quix.Snowflake.Writer/Quix.Snowflake.Writer.csproj -o /buildoutput -r linux-x64 -c Release


FROM mcr.microsoft.com/dotnet/aspnet:7.0-bookworm-slim
WORKDIR /app
COPY --from=build /buildoutput .
ENTRYPOINT dotnet Quix.Snowflake.Writer.dll