FROM python:3.11.1-slim-buster

ENV DEBIAN_FRONTEND="noninteractive"
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8

WORKDIR /app
COPY . .
RUN python3 -m pip install -r requirements.txt
ENTRYPOINT ["python3", "main.py"]