FROM python:3.13-slim-trixie
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8 \
    PYTHONPATH="/app"
ARG MAINAPPPATH=.
WORKDIR /app
COPY "${MAINAPPPATH}/requirements.txt" "${MAINAPPPATH}/requirements.txt"
RUN pip install --no-cache-dir -r "${MAINAPPPATH}/requirements.txt"
COPY . .
WORKDIR "/app/${MAINAPPPATH}"
ENTRYPOINT ["python3", "main.py"]
