# Use the official Prometheus Docker image
FROM prom/prometheus:v3.2.1

# Copy Prometheus configuration file into the container
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Define the default command to run when starting the container
USER root
COPY init.sh /init.sh
RUN chmod +x /init.sh
ENTRYPOINT ["/init.sh"]