FROM ghcr.io/quixio/marimo-base:e6f3041

# Copy your notebook
COPY main.py /app/main.py
COPY icon.png /app/icon.png

# Optional: Copy additional requirements
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt
