/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Aggregation type for data aggregation and down-sampling.                The values reflexts the values inside the NumericAggregation type since the
 */
export type AggregationType = 'None' | 'First' | 'Last' | 'Count';

export const AggregationType = {
    None: 'None' as AggregationType,
    First: 'First' as AggregationType,
    Last: 'Last' as AggregationType,
    Count: 'Count' as AggregationType
};