/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DataSnippet { 
    /**
     * The globally unique identifier of the snippet
     */
    snippetId?: string;
    /**
     * The time the snippet was created at (UTC)
     */
    createdAt?: Date;
    /**
     * The human friendly display name of the snippet
     */
    name?: string;
    /**
     * The ids of the event which belong to this snippet
     */
    eventIds?: Array<string>;
    /**
     * The ids of the numeric parameters which belong to this snippet
     */
    numericParameterIds?: Array<string>;
    /**
     * The ids of the string parameters which belong to this snippet
     */
    stringParameterIds?: Array<string>;
    /**
     * The ids of the streams which belong to this snippet
     */
    streamIds?: Array<string>;
    /**
     * The start time of the snippet in nanoseconds since unix epoch (01/01/1970)
     */
    from?: number;
    /**
     * The end time of the snippet in nanoseconds since unix epoch (01/01/1970)
     */
    to?: number;
}