/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventDataAggregationType } from './eventDataAggregationType';
import { InterpolationType } from './interpolationType';

/**
 * Defines data aggregation settings for events.
 */
export interface EventDataAggregation { 
    aggregationType?: EventDataAggregationType;
    interpolationType?: InterpolationType;
    /**
     * Gets or sets the interval in which the data to be aggregated.
     */
    interval?: number;
}