/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ordering } from './ordering';
import { Paging } from './paging';

export interface GetAllDataSnippetsRequest { 
    /**
     * Filter the data snippets to include only those containing the specified name. This is a case insensitive 'Contains' match. Optional, leave null to not filter by.
     */
    name?: string;
    /**
     * Filter the data snippets to include only those containing the specified parameter ids. This is a case sensitive 'ContainsAny' match. Optional, leave null to not filter by.
     */
    parameterIds?: Array<string>;
    /**
     * Filter the data snippets to include only those containing the specified event ids. This is a case sensitive 'ContainsAny' match. Optional, leave null to not filter by.
     */
    eventIds?: Array<string>;
    /**
     * Filter the data snippets to include only those belonging to the specified stream. This is a case insensitive 'Equals' match. Optional, leave null to not filter by.
     */
    streamId?: string;
    /**
     * The ordering to apply to the resource. Optional, if left null, no ordering is applied
     */
    ordering?: Array<Ordering>;
    paging?: Paging;
}