/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventLevel } from './eventLevel';
import { Ordering } from './ordering';
import { Paging } from './paging';

/**
 * Describes filters for event request
 */
export interface GetAllEventsRequest { 
    /**
     * Filter events to include only those with matching stream ids. Optional, leave null to not filter by.
     */
    streamIds?: Array<string>;
    /**
     * Filter events to include only those with matching location. This is a case sensitive 'StartsWith' match. Optional, leave null to not filter by.
     */
    location?: string;
    /**
     * Filter events to include only those with matching event id. This is a case sensitive 'Equals' match. Optional, leave null to not filter by.
     */
    eventIds?: Array<string>;
    /**
     * Filter events to include only those with matching name. This is a case sensitive 'Contains' match if any capital letter is specified, else case insensitive. Optional, leave null to not filter by.
     */
    name?: string;
    /**
     * Filter events to include only those with matching description. This is a case sensitive 'Contains' match if any capital letter is specified, else case insensitive. Optional, leave null to not filter by.
     */
    description?: string;
    /**
     * Filter events to include only those with matching custom properties. This is a case sensitive 'Equals' match if any capital letter is specified, else case insensitive. Optional, leave null to not filter by.
     */
    customProperties?: string;
    /**
     * Filter the events to include only those with matching level. Optional, leave null to not filter by.
     */
    includeLevels?: Array<EventLevel>;
    /**
     * Filter the events to exclude those with matching level. Optional, leave null to not filter by.
     */
    excludeLevels?: Array<EventLevel>;
    /**
     * The ordering to apply to the resource. Optional, if left null, no ordering is applied
     */
    ordering?: Array<Ordering>;
    paging?: Paging;
}