/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ordering } from './ordering';
import { Paging } from './paging';
import { ParameterType } from './parameterType';

/**
 * Describes filters for parameter request
 */
export interface GetAllParametersRequest { 
    /**
     * Filter parameters to include only those with matching stream ids. Optional, leave null to not filter by.
     */
    streamIds?: Array<string>;
    /**
     * Filter parameters to include only those with matching location. This is a case sensitive 'StartsWith' match. Optional, leave null to not filter by.
     */
    location?: string;
    /**
     * Filter parameters to include only those with matching parameter id. This is a case sensitive 'Equals' match. Optional, leave null to not filter by.
     */
    parameterIds?: Array<string>;
    /**
     * Filter parameters to include only those with matching name. This is a case sensitive 'Contains' match if any capital letter is specified, else case insensitive. Optional, leave null to not filter by.
     */
    name?: string;
    /**
     * Filter parameters to include only those with matching description. This is a case sensitive 'Contains' match if any capital letter is specified, else case insensitive. Optional, leave null to not filter by.
     */
    description?: string;
    /**
     * Filter parameters to include only those with matching unit. This is a case sensitive 'Equals' match if any capital letter is specified, else case insensitive. Optional, leave null to not filter by.
     */
    unit?: string;
    /**
     * Filter parameters to include only those with matching type. Optional, leave null to not filter by.
     */
    includeTypes?: Array<ParameterType>;
    /**
     * Filter parameters to include only those with matching custom properties. This is a case sensitive 'Equals' match if any capital letter is specified, else case insensitive. Optional, leave null to not filter by.
     */
    customProperties?: string;
    /**
     * The ordering to apply to the resource. Optional, if left null, no ordering is applied
     */
    ordering?: Array<Ordering>;
    paging?: Paging;
}