/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AggregationType } from './aggregationType';
import { GroupByTimeSettings } from './groupByTimeSettings';
import { TagFilter } from './tagFilter';

/**
 * Request describing the query for getting parameter data for a data snippet
 */
export interface GetDataSnippetParameterDataRequest { 
    /**
     * The tag filters to apply
     */
    tagFilters?: Array<TagFilter>;
    groupByTime?: GroupByTimeSettings;
    numericAggregation?: AggregationType;
    stringAggregation?: AggregationType;
    /**
     * Collection of tags to group by.
     */
    groupBy?: Array<string>;
}