/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GroupByTimeSettings } from './groupByTimeSettings';
import { NumericParameterAggregation } from './numericParameterAggregation';
import { ParameterAggregation } from './parameterAggregation';
import { TagFilter } from './tagFilter';

export interface GetParameterDataRequest { 
    /**
     * Select numeric parameters in query.
     */
    numericParameters?: Array<NumericParameterAggregation>;
    /**
     * Select string parameters in query.
     */
    stringParameters?: Array<ParameterAggregation>;
    /**
     * Select binary parameters in query.
     */
    binaryParameters?: Array<ParameterAggregation>;
    groupByTime?: GroupByTimeSettings;
    /**
     * Collection of tags to group by.
     */
    groupBy?: Array<string>;
    /**
     * Set to filter data by time.
     */
    from?: number;
    /**
     * Set to filter data by time.
     */
    to?: number;
    /**
     * Set to filter data by stream ID.
     */
    streamIds?: Array<string>;
    /**
     * The tag filters to apply
     */
    tagFilters?: Array<TagFilter>;
}