/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TagFilter } from './tagFilter';

export interface GetTagValuesRequest { 
    tagKey?: string;
    /**
     * Set to filter data by time.
     */
    from?: number;
    /**
     * Set to filter data by time.
     */
    to?: number;
    /**
     * Set to filter data by stream ID.
     */
    streamIds?: Array<string>;
    /**
     * The tag filters to apply
     */
    tagFilters?: Array<TagFilter>;
}