/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Set interpolation for data upscaling. (When group by time is enabled and data missing between timestamps)
 */
export type InterpolationType = 'None' | 'Linear' | 'Null' | 'Previous';

export const InterpolationType = {
    None: 'None' as InterpolationType,
    Linear: 'Linear' as InterpolationType,
    Null: 'Null' as InterpolationType,
    Previous: 'Previous' as InterpolationType
};