/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes filters for Metadata Key and/or Value
 */
export interface MetadataFilter { 
    /**
     * Key to filter by. Optional. This is a case sensitive 'Equals' match. Leave null to not filter by.
     */
    key?: string;
    /**
     * Value to filter by. Optional. This is a case sensitive 'Equals' match. Leave null to not filter by.
     */
    value?: string;
}