/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrderDirection } from './orderDirection';

/**
 * Describes resource ordering
 */
export interface Ordering { 
    /**
     * The property to order by
     */
    by?: string;
    direction?: OrderDirection;
}