/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The possible parameter types
 */
export type ParameterType = 'Unknown' | 'Numeric' | 'String' | 'Binary';

export const ParameterType = {
    Unknown: 'Unknown' as ParameterType,
    Numeric: 'Numeric' as ParameterType,
    String: 'String' as ParameterType,
    Binary: 'Binary' as ParameterType
};