/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ParameterType } from './parameterType';

/**
 * Describes properties of a parameter
 */
export interface Parameter { 
    /**
     * Primary Identifier of the parameter
     */
    parameterId?: string;
    /**
     * Display name of the parameter
     */
    name?: string;
    /**
     * Description of the parameter
     */
    description?: string;
    /**
     * Minimum value of the parameter
     */
    minimumValue?: number;
    /**
     * Maximum value of the parameter
     */
    maximumValue?: number;
    /**
     * Unit of the parameter
     */
    unit?: string;
    /**
     * Format of the parameter
     */
    format?: string;
    /**
     * Optional field for any user defined custom properties.  This could be a json string, describing the optimal value range of this parameter
     */
    customProperties?: string;
    /**
     * The stream id(s) the parameter belongs to.  If parameters are queried for multiple streams, the streams that have this parameter will have their ids listed here
     */
    streamIds?: Array<string>;
    /**
     * Location of the parameter within the parameter group hierarchy
     */
    location?: string;
    type?: ParameterType;
}