/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes properties of a parameter group
 */
export interface ParameterGroup { 
    /**
     * The absolute path to the group in the hierarchy  Also serves as an unique identifier
     */
    path?: string;
    /**
     * The display name of the group
     */
    name?: string;
    /**
     * The description of the group
     */
    description?: string;
    /**
     * Optional field for any user defined custom properties.  This could be a json string, describing the relationship between parameters
     */
    customProperties?: string;
    /**
     * The stream id(s) the group belongs to.  If groups are queried for multiple streams, the streams that have this group will have their ids listed here
     */
    streamIds?: Array<string>;
    /**
     * Location of the group within the parameter group hierarchy
     */
    location?: string;
    /**
     * The number of parameter groups this group contains
     */
    childrenCount?: number;
}