/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Status of the stream
 */
export type StreamStatus = 'Open' | 'Closed' | 'Aborted' | 'Terminated' | 'Interrupted' | 'Deleting' | 'SoftDeleted' | 'Idle';

export const StreamStatus = {
    Open: 'Open' as StreamStatus,
    Closed: 'Closed' as StreamStatus,
    Aborted: 'Aborted' as StreamStatus,
    Terminated: 'Terminated' as StreamStatus,
    Interrupted: 'Interrupted' as StreamStatus,
    Deleting: 'Deleting' as StreamStatus,
    SoftDeleted: 'SoftDeleted' as StreamStatus,
    Idle: 'Idle' as StreamStatus
};