/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TagOperator } from './tagOperator';

/**
 * The filter used to further limit the returned values
 */
export interface TagFilter { 
    /**
     * The tag
     */
    tag?: string;
    operator?: TagOperator;
    /**
     * The value(s) to compare to values present in the database.  Accepted: string, numeric types and enumerable of these.  Example: \"string\", 23.32, [1.2, 2, 3.4], [\"one\", \"two\"]
     */
    value?: any;
}