/**
 * Telemetry Query API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The allowed tag operations
 */
export type TagOperator = 'Equal' | 'NotEqual' | 'Like' | 'NotLike';

export const TagOperator = {
    Equal: 'Equal' as TagOperator,
    NotEqual: 'NotEqual' as TagOperator,
    Like: 'Like' as TagOperator,
    NotLike: 'NotLike' as TagOperator
};