# Stage 1: Build the React application
FROM node:14 as build
WORKDIR /app
COPY ./package*.json ./
RUN npm install
COPY . /app/
RUN npm run build

# Stage 2: Serve the React application using Nginx
FROM nginx:1.25.3-bookworm
COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./run_server.sh /

RUN chmod +x /run_server.sh
RUN chown -R nginx:nginx /usr/share/nginx/html && chmod -R 755 /usr/share/nginx/html

CMD ["/run_server.sh"]
