FROM mathworks/matlab:r2023b

USER root

# Install Python dependencies
RUN apt-get update && apt-get install -y \
    python3.10 python3.10-dev python3.10-venv

# Switch back to the original user (if needed)
USER matlab

ENV MW_LICENSING_DIAGNOSTICS=1

ENV MLM_LICENSE_FILE=27000@your-license-server

# Add MATLAB Runtime to LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=/opt/matlab/R2024b/bin/glnxa64:$LD_LIBRARY_PATH

# Install the MATLAB Engine API for Python
RUN pip3 install matlabengine==23.2.3

# Copy your Python script into the image
COPY main.py /app/main.py

# Set Python as the default entry point
ENTRYPOINT ["python", "/app/main.py"]